"""
Smoke test config for Azure VM validation.

Tiny model (d_model=128, 2 blocks) with 20 steps on synthetic tokens.
Purpose: verify compile+DDP works, checkpoint save/load works, and data pipeline
flows end-to-end before committing to a 5-day 92B-token run.

Expected runtime: ~1-2 minutes on 8x H100.
"""

CONFIG = {
    # ---- Model (tiny for speed) ----
    "tier":            "nano",
    "d_model":         128,
    "n_blocks":        2,
    "n_heads":         4,
    "context_len":     256,
    "top_k":           8,
    "mem_depth":       4,
    "max_gists":       16,
    "gist_top_k":      2,
    "dropout":         0.0,

    # ---- Tokenizer (fake vocab size for smoke test) ----
    "use_tmt_tokenizer": False,  # use simple vocab
    "vocab_size":        32000,

    # ---- Training (20 steps only) ----
    "steps":           20,
    "batch_size":      2,                  # per GPU
    "grad_accum_steps": 1,
    "world_size":      8,
    "lr":              1e-3,
    "betas":           (0.9, 0.95),
    "weight_decay":    0.01,
    "warmup_steps":    5,

    # ---- System ----
    "gradient_checkpoint": False,  # not needed for tiny model
    "compile":             True,   # test compile+DDP interaction
    "compile_mode":        "max-autotune",
    "use_8bit_optimizer":  False,
    "amp_dtype":           "bfloat16",
    "gc_every":            100,
    "eval_every":          10,
    "ckpt_every":          10,     # checkpoint at step 10 to test resume
    "keep_last_ckpts":     2,

    # ---- Data (smoke tokens generated by smoke_tokens.py) ----
    "tokens_dir": "/mnt/blob/tokens/smoke",
    "val_split":   0.01,

    # ---- Logging / output ----
    "wandb_project": None,  # disable WandB for smoke test
    "output_dir":    "/mnt/blob/checkpoints/smoke",

    "seed": 42,
}
